#!/usr/bin/env node
console.log("commit");
const arg = process.argv.slice(2)[0];
const fs = require('fs');
const fileString = fs.readFileSync(arg, { encoding: 'utf8', flag: 'r' });
const message = fileString.trim();

if (!/^\d+\s/.exec(message.toLowerCase())) {
  console.log('\nНазвание коммита должно начинаться с цифр');
  process.exit(1);
}